image: python:latest

before-sript:
    - python -V


stages:          
  - test
  - style

unittest-job:
    stage: test
    before_script:
        - pip install django
        - pip install coverage
    script:
        - coverage run manage.py runserver
        - coverage report
        - coverage html
        - mkdir public
        - mv htmlcov public/coverage

    artifacts:
        paths:
            public/coverage

