image: python:latest

before_script:
    - python -V

stages:          # List of stages for jobs, and their order of execution
  - test
  - style

unittest-job:
    stage: test
    before_script:
        - pip install django
        - pip install django-crispy-forms
        - pip install django-debug-toolbar
        - pip install coverage

    script:
        - coverage run manage.py runserver
        - coverage report
        - coverage html
        - mkdir public
        - mv htmlcov public/coverage

    artifacts:
        paths:
            - public/coverage


codestyle-job:
    stage: style
    before_script:
        - pip install pylint

    script:
        - ./ci/pylint_script.sh

    artifacts:
        paths:
            - public/pylint.svg
            - public/pylint.html

