image: python:latest

before_script:
    - python -V


stages:          
  - test
  - style

unittest-job:
    stage: test
    before_script:
        - pip install django
        - pip install django-crispy-forms
        - pip install django-debug-toolbar
        - pip install coverage
    script:
        - coverage run manage.py runserver
        - coverage report
        - coverage html
        - mkdir public
        - mv htmlcov public/coverage

    artifacts:
        paths:
            - public/coverage

pylint:
  stage: style
  before_script:
    - pip install pylint
  script:
      - cd main
      - pylint -j 2 views.py models.py
  artifacts:
    paths:
        - public/pylint.svg
        - public/pylint.html

