# Generated by Django 4.0.3 on 2022-04-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_creator', models.CharField(max_length=50)),
                ('country_creator', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.IntegerField()),
                ('name_product', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('creator_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('country_product', models.CharField(max_length=50)),
                ('category_id', models.IntegerField()),
            ],
        ),
    ]
