# Generated by Django 3.2.16 on 2023-03-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230301_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.IntegerField()),
                ('brand', models.CharField(max_length=50, null=True)),
                ('model', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('description1', models.CharField(max_length=400, null=True)),
                ('description2', models.CharField(max_length=400, null=True)),
                ('description3', models.CharField(max_length=400, null=True)),
                ('image', models.ImageField(upload_to='static/images/collection')),
            ],
        ),
    ]
