# Generated by Django 3.2.16 on 2023-03-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='mainimg',
            field=models.ImageField(null=True, upload_to='static/images/blog'),
        ),
    ]
