# Generated by Django 3.2.16 on 2023-03-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20230308_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title1',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title2',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title3',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
