# Generated by Django 3.2.16 on 2023-03-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20230308_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('phonenumber', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
