# Generated by Django 3.2.16 on 2023-03-12 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_productpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpoint',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
