# Generated by Django 3.2.16 on 2023-03-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_productpoint_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpoint',
            name='product',
        ),
    ]
